### ISSUE TITLE
Too many nonzeros

### ISSUE THREAD

**Issue by bhezy** [carlos-souto/Sparse-Matrix-Builder#2]
Hello!

I am trying to create a 2608527 x 2608527 matrix using your code with 397250496 nonzeros on my 128 GB RAM system with a Ryzen 5800 CPU. I get the following error:

No method 'Set' with matching signature found for class
'SparseLibrary.SparseMatrixBuilder'.

Error in Step_02_Compute_BCs_and_K (line 74)
K = test_custom(ndof, ndof, iK(:), jK(:), sK(:));

ONLY when using that many nonzeros. If I take it down to 39725049 nonzeros (dropping the 6 up above), it works. However, I need it to work for the entire set of nonzeros. I believe that the issue may be hidden behind the base definition.

I would like to add that sparse in matlab can do it within 8 seconds, so I bet your algorithm can do it much faster if it doesn't encounter this error. The failing command is 0.0058% full, so VERY sparse.

EDIT - I get this error message when I use 1/2 the original number of nonzeros, which is more descriptive interestingly:

Error using SparseMatrixBuilder/Set
Message: Array dimensions exceeded supported range.
Source: mscorlib
HelpLink: None

Error in Step_02_Compute_BCs_and_K>test_custom (line 91)
    matrix.Set(rows, cols, vals);

Error in Step_02_Compute_BCs_and_K (line 75)
K = test_custom(ndof, ndof, iK(1:round(397250496*2/4)), jK(1:round(397250496*2/4)), sK(1:round(397250496*2/4)));

-Ben

**Comment by carlos-souto** [comment]
Without a minimal working example it is hard to identify the problem. Nevertheless, I updated the repository with a completely new and simplified version written purely in Matlab. This version should be faster than the previous if you are building a sparse matrix inside some loop. Notice, however, that this current version has limited functionality: you can only add elements to the matrix (repeated elements will be added together); you cannot set a specific entry to a value (only add to it); you cannot get values. If you want to set/get values, first convert the `SparseMatrixBuilder` to a Matlab `sparse` matrix using the `to_sparse()`method. See the new readme.

Let me know if this new version helps you.
